### ISSUE TITLE
crossenv was compromised

### ISSUE THREAD

**Issue by ArtskydJ** [mattbis/ksb-base#1]
https://twitter.com/o_cee/status/892306836199800836

If you have anything sensitive in your environment variables, then they were probably leaked.

**Comment by mattbis** [comment]
I've not used; I was planning to make things os neutral in future with potentially using it.. Perhaps in using in something I intend to publish I might have checked out the code.. Its hard to say... And easy to miss.. Which reminds me to put this into another idea I have been thinking of for code introspection... [ or to find something that satisfies this ]

**Comment by mattbis** [comment]
maybe have to go up a language level as this can be done quite nicely in Python

**Comment by mattbis** [comment]
Or falafel and stuff like that.. hmm...

**Comment by mattbis** [comment]
Many Thanks! Was aware of this... I gave up cross platform some time ago :)
